### ISSUE TITLE
Consider generating code... somehow

### ISSUE THREAD

**Issue by alteous** [gltf-rs/gltf#198]
#19 discussed the idea of generating code from the official glTF JSON schema. Whilst this was impractical at the time (and will likely still be impractical) I'd like to reconsider the idea.

The main advantage of generating code is to reduce labour-intensive and error-prone repetition of boilerplate code such as our data structure definitions, `Validate` implementations, and iterators.  The main disadvantage is the additional level of indirection when making changes and reasoning about the crate code.

If we do generate code, it might be sensible to create our own version of the glTF schema specific to our needs. The alternative is a set of custom rules based on the glTF path, for example, '`extensions` resolves to an `Extensions` struct.

**Comment by alteous** [comment]
If the `Checked` type is removed in favour of `Enum::Extension(_)` options then I think we have enough information in the `gltf_json` code to generate the corresponding wrapper. This also cleans up the `gltf_json` code for export case.

### Example

Consider `gltf_json::accessor::Type`:

#### Before/Current

```rust
enum Type {
    Scalar,
    Vec2,
    ...,
    Mat4,
}

struct Accessor {
    pub type_: Checked<Type>, // will be set to `Invalid` if not in the list above
}
```

#### After

```rust
enum Type {
    Scalar,
    Vec2,
    ...,
    Mat4,
    Extension(u32), // we assume unknown values are those belonging to extensions
}

struct Accessor {
    pub type_: Type, // no longer requires validation
}
```

**Comment by alteous** [comment]
If generating with a procedural macro then we need to be able to copy the documentation over similar to https://github.com/shepmaster/snafu/issues/106.

**Comment by alteous** [comment]
I have an experimental procedural macro over at https://github.com/alteous/gltf-codegen-experiment that copies documentation successfully.

**Test input**
```rust
/// Docs.
#[gltf_codegen2::hello]
fn world() {}

#[test]
fn works() {
    world();
}
```

**Test output**
```
$ cargo test --quiet -- --nocapture | grep Hello
Hello world! " Docs."
```

**Generated code**
```
$ cargo expand --test smoke | grep -B 1 -A 12 "fn world"
    Checking gltf-codegen2 v0.1.0 (/home/alteous/gltf-codegen2)
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s

/// Docs.
fn world() {
    {
        ::std::io::_print(::std::fmt::Arguments::new_v1(
            &["Hello ", "! ", "\n"],
            &match (&"world", &" Docs.") {
                (arg0, arg1) => [
                    ::std::fmt::ArgumentV1::new(arg0, ::std::fmt::Display::fmt),
                    ::std::fmt::ArgumentV1::new(arg1, ::std::fmt::Debug::fmt),
                ],
            },
        ));
    };
}
```

The important part is that the documentation is retained:

```rust
/// Docs.
fn world() {
...
```

**Comment by alteous** [comment]
On second thoughts, I don't think removing the `Checked` type is a good idea. Extensions are 'opt-in' for glTF, meaning an asset must list all extensions required to load and render itself. The `Checked` type ensures enumeration values are always valid and the `import` function rejects glTF that require unsupported extensions by the crate. Passing these burdens onto the user will make it more difficult to support glTF in their application, which is against the philosophy of this crate.

I propose instead we continue with 'builder' abstractions for the JSON but remove indirection of `Index`/`Checked` types.

```rust
struct RawAccessor {
    pub buffer_view: Index<buffer::View>,
    pub component_type: Checked<GenericComponentType>,
    pub byte_offset: u32,
}

struct AccessorBuilder;

impl AccessorBuilder {
    /// Instead of `Index<buffer::View>`
    pub fn buffer_view<T>(&mut self, buffer_view: T) -> &mut self
        where T: Into<Index<buffer::View>>
    {
         // Usage: builder.buffer_view(123) or builder.buffer_view(&buffer_view)
        self
    }

    /// Instead of `Checked<GenericComponentType>`
    pub fn component_type(&mut self, component_type: ComponentType) -> &mut self {
         // Usage: builder.component_type(Component::TypeF32)
        self
    }

    /// Trivial wrapper.
    pub fn byte_offset(&mut self, byte_offset: u32) -> &mut self {
         // Usage: builder.byte_offset(4)
        self
    }
}
```

**Comment by alteous** [comment]
By moving to the generated accessors and builders we will have to remove the `Sampler::animation` and `Channel::animation` functions. This is probably not a big deal as you need the parent animation struct to get the sampler and channel structs anyway.

**Comment by alteous** [comment]
I've been experimenting with [generating from custom data](https://github.com/alteous/gltf-codegen-experiment/tree/master/toml), written in TOML format. This should be familiar to Rust programmers as it's the same format Cargo uses for configuration. The code generation task has been much smoother this way.

#### Example input data

`toml/accessor::Accessor`:
```toml
[meta]
kind = "enum"
ty = "string"
docs = "Component type."

[values]
F32 = { docs = "32 bit floating point" }
I32 = { docs = "32 bit signed integer" }
```

`toml/buffer::Buffer`
```toml
[meta]
kind = "struct"
docs = "A buffer points to binary geometry, animation, or skins."

[fields]
uri = { ty = "String", docs = "URI to buffer data." }
foo = { ty = "Index", of = "Accessor", docs = "Index of accessor."  }
bar = { ty = "Enum", of = "ComponentType", docs = "Component type." }
```

`toml/texture::MinFilter`
```toml
[meta]
docs = "Minification filter."
kind = "enum"
ty = "integer"

[values]
Nearest = { value = 9728, docs = "Nearest filter." }
Linear = { value = 9729, docs = "Linear filter." }
```

This has been the smoothest development journey so far.
